services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config:/config
    
      
    restart: unless-stopped
    privileged: true
    ports:
    - "8123:8123"
    networks:
      - mqtt
  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"   # Puerto MQTT
      - "7070:7070"   # Puerto MQTT (sin SSL)
      
      
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      - mqtt

networks:
      mqtt:
        name: MQTT